version: "3.6"
services:
  mispartidostv:
    container_name: mispartidostv
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: ../
      dockerfile: deployments/Dockerfile
      args:
        python_version: ${PYTHON_VERSION}
        app_version: ${IMAGE_VERSION}
    volumes:
      - ../app:/usr/src/app
    command: bash
    tty: true
