version: '3.8'
services:
  mispartidostv:
    container_name: mispartidostv
    image: mispartidostv
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    volumes:
      - ../app:/usr/src/app
    env_file:
      - ../app/.env
    command: sh
    tty: true
