name: Run application

on:
  schedule:
    - cron: 0 6 * * *

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  Run:
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - uses: actions/checkout@v3
      - name: Run mispartidostv application
        run: docker run -e TODOIST_TOKEN=${{ secrets.TODOIST_TOKEN }} ghcr.io/francisjgarcia/mispartidostv:latest
