name: Run application

on:
  schedule:
    - cron: 0 6 * * *
  workflow_dispatch:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  Run:
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run mispartidostv application
        run: docker run -e TODOIST_TOKEN=${{ secrets.TODOIST_TOKEN }} ghcr.io/francisjgarcia/mispartidostv:latest
