name: Docker image build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Get tag version
        run: |
          if ${{ github.ref == 'refs/heads/master' }}; then
            echo DOCKER_IMAGE_TAG="latest" >> $GITHUB_ENV
          elif ${{ startsWith(github.ref, 'refs/tags/v') }}; then
            echo DOCKER_IMAGE_TAG=$(echo "${GITHUB_REF##*/}" | cut -c2-) >> $GITHUB_ENV
          fi
          echo DOCKER_REPOSITORY_NAME=$(echo "${GITHUB_REPOSITORY}") >> $GITHUB_ENV

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./deployments/Dockerfile
          tags: ${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
