name: Run application

on:
  schedule:
    - cron: 0 6 * * *

env:
    TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mispartidostv application
        run: docker run -e TODOIST_TOKEN=$TODOIST_TOKEN francisjgarcia/mispartidostv:latest
